### ISSUE TITLE
use a toplevel package

### ISSUE THREAD

**Issue by nadako** [vshaxe/vscode-debugadapter-extern#1]
I'm a bit uncomfortable with how this library provide toplevel `adapter` and `protocol` packages. This is too generic IMO and can possibly clash with other libraries or user code.

What about we kind of follow the upstream module naming (`vscode-debugprotocol` + `vscode-debugadapter`) and have: `vscodeDebugProtocol` and `vscodeDebugAdapter` toplevel packages?

Also I would like to split the extern types into separate modules like we did in the [vscode-extern](https://github.com/vshaxe/vscode-extern/tree/master/src/vscode).

**Comment by Gama11** [comment]
Went with something quite similar to what you suggested, but replacing `-` with `.`:

- `vscode.debugProtocol`
- `vscode.debugAdapter`
- `vscode.debugAdapter.testSupport`
